name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: "17.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build-all

      - name: Run unit tests
        run: npm test

      - name: Upload coverage report
        uses: codecov/codecov-action@v2.1.0
        with:
          name: Production
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/clover.xml,./coverage/coverage-final.json,./coverage/lcov.info
          flags: unittests
          verbose: true

      - name: Create tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump manifest version
        env:
          tag: ${{steps.tag_version.outputs.new_version}}
        run: |
          sed 's/"version":"[^"]*"/"version": "'$tag'"/' dist/crx/manifest.json | tee dist/crx/manifest.json
          sed 's/"version":"[^"]*"/"version": "'$tag'"/' dist/xpi/manifest.json | tee dist/xpi/manifest.json

      - name: Package distribution
        run: |
          (cd dist/crx; zip ../../dist.crx -r *) & \
          (cd dist/xpi; zip ../../dist.xpi -r *)

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist.crx
            dist.xpi
          tag_name: ${{steps.tag_version.outputs.new_tag}}
          prerelease: false
          draft: false
          generate_release_notes: true
          fail_on_unmatched_files: true

      - name: Publish to Chrome Store
        uses: mnao305/chrome-extension-upload@2.2.0
        with:
          file-path: "./dist.crx"
          extension-id: ${{secrets.CHROME_APP_ID}}
          client-id: ${{secrets.CHROME_CLIENT_ID}}
          refresh-token: ${{secrets.CHROME_REFRESH_TOKEN}}
          publish: true

      - name: Publish to Firefox Store
        uses: trmcnvn/firefox-addon@v1
        with:
          uuid: ${{secrets.FIREFOX_UUID}}
          xpi: "./dist.xpi"
          manifest: dist/xpi/manifest.json
          api-key: ${{secrets.FIREFOX_API_KEY}}
          api-secret: ${{secrets.FIREFOX_API_SECRET}}
