name: Pull Request

on:
  pull_request:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "17.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build
        run: npm run build-all --if-present

      - name: Run unit tests
        run: npm run cover

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: "coverage report"
          path: ./coverage/lcov-report
